export const citiesData = {
    amsterdam: {
        country: "Netherlands",
        population: "905 000",
        information: "Amsterdam is colloquially referred to as the \"Venice of the North\", due to the large number of canals which form a UNESCO World Heritage Site. Originating as a small fishing village in the late 12th century, Amsterdam became one of the most important ports in the world during the Dutch Golden Age of the 17th century, and became the leading centre for the finance and trade sectors. In the 19th and 20th centuries, the city expanded and many new neighborhoods and suburbs were planned and built.  Primarily known for its artistic heritage, elaborate canal system and narrow houses with gabled façades; well-preserved legacies of the city's 17th-century Golden Age. These characteristics are arguably responsible for attracting millions of Amsterdam's visitors annually. Cycling is key to the city's character, and there are numerous biking paths and lanes spread throughout the entire city.",
        picUrl: "https://cdn.britannica.com/30/180130-138-4FC01CDD/Overview-Amsterdam.jpg?w=800&h=450&c=crop",
    },
    barcelona: {
        country: "Spain",
        population: "1 620 000",
        information: "Barcelona is the capital and largest city of the autonomous community of Catalonia, as well as the second most populous municipality of Spain. Barcelona has a rich cultural heritage and is today an important cultural centre and a major tourist destination. Particularly renowned are the architectural works of Antoni Gaudí and Lluís Domènech i Montaner, which have been designated UNESCO World Heritage Sites. Especially remarkable is the work of architect Antoni Gaudí, which can be seen throughout the city. His best-known work is the immense but still unfinished church of the Sagrada Família, which has been under construction since 1882 and is still financed by private donations. As of 2015, completion is planned for 2026. Another masterpiece by Gaudi is the Park Guell. The park supports a wide variety of wildlife, notably several of the non-native species of parrot found in the Barcelona area. Other birds can be seen from the park, with records including short-toed eagle. The park also supports a population of hummingbird hawk moths.",
        picUrl: "https://www.flytap.com/-/media/Flytap/new-tap-pages/destinations/europe/spain/barcelona/barcelona-og-image-v2-1200x630.jpg"
    },
    chalkidiki: { 
        country: "Greece", 
        population: "106 000", 
        information: "Chalkidiki is a peninsula and regional unit of Greece, part of the region of Central Macedonia, in the geographic region of Macedonia in Northern Greece. The autonomous Mount Athos region constitutes the easternmost part of the peninsula, but not of the regional unit. The capital of Chalkidiki is the town of Polygyros, located in the centre of the peninsula, while the largest town is Nea Moudania. Chalkidiki is a popular summer tourist destination. The large peninsula is located in the northwestern Aegean Sea, resembling a hand with three 'fingers'. From west to east, these are Kassandra, Sithonia, and Mount Athos, a special polity within Greece known for its monasteries. These \"fingers\" are separated by two gulfs, the Toronean Gulf and the Singitic Gulf. Chalkidiki has been a popular summer tourist destination since the late 1950s when people from Thessaloniki started spending their summer holidays in the coastal villages. In the beginning tourists rented rooms in the houses of locals. By the 1960s, tourists from Austria and Germany started to visit Chalkidiki more frequently. Since the start of the big tourist boom in the 1970s, the whole region has been captured by tourism.", 
        picUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-DJETTk6hQH39n2F-P7YkeqJWXwOyvSnUAQ&usqp=CAU" 
    },
    corfu: {
        country: "Greece", 
        population: "102 000", 
        information: "Corfu or Kerkyra is a Greek island in the Ionian Sea, of the Ionian Islands, and, including its small satellite islands, forms the margin of the northwestern frontier of Greece. The island is bound up with the history of Greece from the beginnings of Greek mythology, and is marked by numerous battles and conquests. Ruins of ancient Greek temples and other archaeological sites of the ancient city of Korkyra are found in Palaiopolis. Medieval castles punctuating strategic locations across the island are a legacy of struggles in the Middle Ages against invasions by pirates and the Ottomans. Two of these castles enclose its capital, which is the only city in Greece to be surrounded in such a way. As a result, Corfu's capital has been officially declared a Kastropolis (\"castle city\") by the Greek government. In 2007, the city's old town was added to the UNESCO World Heritage List. Corfiotes have a long history of hospitality to foreign residents and visitors. ", 
        picUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJrAV-EUSswkToyJxs2PY1cO9kZvkE9lDdaw&usqp=CAU"},
    heidelberg: {
        country: "Germany", 
        population: "159 000", 
        information: "Heidelberg is a city in the German state of Baden-Württemberg, situated on the river Neckar in south-west Germany. Heidelberg University, founded in 1386, is Germany's oldest and one of Europe's most reputable universities. Heidelberg is a scientific hub in Germany and home to several internationally renowned research facilities adjacent to its university. The city has also been a hub for the arts, especially literature, throughout the centuries, and it was designated a \"City of Literature\" by the UNESCO Creative Cities Network. It is a popular tourist destination due to its romantic cityscape, including Heidelberg Castle, the Philosophers' Walk, and the Baroque old town. The castle is a mix of styles from Gothic to Renaissance. Prince Elector Ruprecht III (1398–1410) erected the first building in the inner courtyard as a royal residence. Although the interior is in Gothic style, the King's Hall was not built until 1934. Today, the hall is used for festivities, e.g. dinner banquets, balls and theatre performances. During the Heidelberg Castle Festival in the summer, the courtyard is the site of open air musicals, operas, theatre performances, and classical concerts performed by the Heidelberg Philharmonics.", 
        picUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4E1r8acb-lvzJ0WHDkWrmTSGj8m7Id9Ajtw&usqp=CAU"
    },
    krushuna: {
        country: "Bulgaria", 
        population: "383", 
        information: "Krushuna is a village in Letnitsa Municipality, Lovech Province, northern Bulgaria. It is famous for the nearby waterfalls with their picturesque landscape and formation by many travertines. There is a tourist path leading to the cave where the river springs. There are two smaller waterfalls in the area, one of which is called Malkata Maara. Some other caves are also found in the vicinity - Urushka Maara, Gornik, Devetashka cave. The Devetashka cave is a large karst cave that served as a shelter for Paleo humans for tens of thousands of years, as well as various faunal species during extensive periods and is now home to nearly 30,000 bats. Remains of the 13-14th century Hesychast Krushuna Monastery dating from the Second Bulgarian Empire can be found nearby. ", 
        picUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXUM9LFPuCXgZn40uX9mvtSPmDp3BkzPDAIQ&usqp=CAU"
    },
    lagos: {
        country: "Portugal", 
        population: "31 000", 
        information: "Lagos is an ancient maritime town with more than 2000 years of history. The name Lagos comes from a Celtic settlement, derived from the Latin Lacobriga, the name of the settlement was established during the pre-Punic civilizations. It became an early settlement of the Carthaginians. With the fall of Rome, the town of Lagos was occupied in the sixth century by the Visigoths from the Kingdom of Toledo and later by the Byzantines. The Moors arrived in the 8th century from North Africa, renaming the settlement Zawaia. awaia was eventually captured by King Afonso III of Portugal in 1241. King John I assembled his fleet in the harbour of Lagos, before setting sail for the siege and conquest of the city of Ceuta in 1415. This was the first step in opening the Muslim world to medieval Europe. From 1576 to 1755, Lagos was a high-profile capital of the Algarve, until the old Portuguese town was destroyed by the earthquake and tsunami of 1755. Although some walls from the 16th century still remain, as well as the governor's castle, many of the buildings are from the 17th century. Today Lagos is one of the most visited cities in the Algarve and Portugal, due to its variety of tourist-friendly beaches, rock formations (Ponta da Piedade), bars, restaurants and hotels, renowned for its vibrant summer nightlife and parties. ", 
        picUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsEMfd-pQOVLwWdNm7LKgjo9fstSwpNXRAqw&usqp=CAU"},
    rila: {
        country: "Bulgaria", 
        population: "-",
        information: "Rila is the highest mountain range of Bulgaria, the Balkan Peninsula and Southeast Europe. It is situated in southwestern Bulgaria and forms part of the Rila-Rhodope Massif. The highest summit is Musala at an altitude of 2,925 m which makes Rila the sixth highest mountain range in Europe. It spans a territory of 2,629 km2 with an average altitude of 1487 m. Rila has abundant water resources. Some of the Balkans' longest and deepest rivers originate from Rila, including the Maritsa, Iskar and Mesta rivers. The mountain range is dotted with almost 200 glacial lakes such as the renowned Seven Rila Lakes. The Seven Rila Lakes are situated between 2,100 and 2,500 metres elevation above sea level. Each lake carries a name associated with its most characteristic feature. The highest one is called Salzata (\"The Tear\") due to its clear waters that allow visibility in depth. The next one in height carries the name Okoto (\"The Eye\") after its almost perfectly oval form. Okoto is the deepest cirque lake in Bulgaria, with a depth of 37.5 m. Babreka (\"The Kidney\") is the lake with the steepest shores of the entire group. Bliznaka (\"The Twin\") is the largest one by area. Trilistnika (\"The Trefoil\") has an irregular shape and low shores. The shallowest lake is Ribnoto Ezero (\"The Fish Lake\") and the lowest one is Dolnoto Ezero (\"The Lower Lake\").", 
        picUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwb_DPF-gQL-aQRxZWXjzEO4tj8YZkJWGVLA&usqp=CAU"},
    tenerife: {
        country: "Spain", 
        population: "966 000", 
        information: "Tenerife is the largest and most populous island of the Canary Islands. It is home to 43% of the total population of the archipelago. With a land area of 2,034 square kilometres (785 sq mi) and a population of 966,354 inhabitants at the end of 2020, it is also the most populous island of Spain and of Macaronesia. Approximately five million tourists visit Tenerife each year; it is the most visited island in the archipelago. It is one of the most important tourist destinations in Spain and the world, hosting one of the world's largest carnivals, the Carnival of Santa Cruz de Tenerife. Teide National Park, located in the center of the island, is also a UNESCO World Heritage Site. It includes Mount Teide, which has the highest elevation in Spain, and the highest among all the islands in the Atlantic Ocean. It is also the third-largest volcano in the world, when measured from its base. The volcano is visible from most parts of the island today, and the crater is 17 kilometres (11 miles) long at some points. Another geographical feature of the island, the Macizo de Anaga (massif), has been designated as a UNESCO Biosphere Reserve since 2015. Tenerife also has the largest number of endemic species in Europe. ", 
        picUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcr76fyYk-_mTVCsmSmmZiIT3hS3s5kvRuGg&usqp=CAU"},
};
